### ISSUE TITLE
Kreiranje sastavnice, datum kreiranja

### ISSUE THREAD

**Issue by AhmAli** [SoftverInzenjeringETFSA/SI2014Tim1#100]
Komponenta:
FZaposlenik

commit ID:
e51cebc

Opis problema:
Nedostaje datum kreiranja sastavnice pri kreiranju nove sastavnice.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju 
2. Ulogovati se kao korisnik
3. Odabrati Sastavnice
4. Kreirati novu sastavnicu.

![image](https://cloud.githubusercontent.com/assets/6852893/7898654/cf02317c-0706-11e5-9f99-51cd0733e79b.png)

Dobijeni rezultat:
Kreirana sastavnica bez datuma kreiranja

Očekivani rezultat:
Kompletni podaci uključujući datum kreiranja.

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 154faa45e5b5cd512dbe4f5090bb882a6d140b05
