### ISSUE TITLE
Pregled nove sastavnice nema prikaza

### ISSUE THREAD

**Issue by AhmAli** [SoftverInzenjeringETFSA/SI2014Tim1#101]
Komponenta:
FZaposlenik

commit ID:
e51cebc

Opis problema:
Nakon kreiranja nove sastavnice nije dostupan sam Pregled navedene sastavnice.

![image](https://cloud.githubusercontent.com/assets/6852893/7898671/865e431a-0707-11e5-93ea-08b7367f19a7.png)

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju 
2. Ulogovati se kao korisnik
3. Odabrati Sastavnice
4. Kreirati novu sastavnicu
5.Odabrati novo kreiranu sastavnicu sa liste za pregled

Dobijeni rezultat:
Nije dostupan prikaz sastavnice.

Očekivani rezultat:
Prikaz sastavnice.

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 154faa45e5b5cd512dbe4f5090bb882a6d140b05
