### ISSUE TITLE
Modifikacija materijala/poluproizvoda

### ISSUE THREAD

**Issue by akadrispahic** [SoftverInzenjeringETFSA/SI2014Tim1#102]
Komponenta: FZaposlenik
Commit :
e51cebc

Opis problema:
Nema poruke, da li je uspješno izvršena promjena materijala, npr. naziva ili količine.
Promjenila sam naziv i količinu, na odabir dugmeta nazad ništa se ne desi.

Koraci za reprodukciju:
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara zaposleniku (npr Korisničko ime : prviradnik; šifra : prviradnik)
2.Otvoriti polje skladište
3.Selektovati red, tj. materijal koji želimo modifikovati
4. Odabrati dugme Modifikuj
5. Izmjena nekih od parametara u formi Modifikacija materijala/poluproizvoda

Dobijeni Rezultati
![888](https://cloud.githubusercontent.com/assets/11389876/7898683/0510433e-0708-11e5-8a35-a068c341f83e.jpg)

Očekivani rezultati:
Izbaciti poruku o uspješnoj modifikaciji, ili po potrebi ErrorProvider sa porukom koja objašnjava u čemu je problem.

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 866c50776e937bf40a28cef41a6897c8aa6585e5
