### ISSUE TITLE
Modifikacija sastavnice nije moguća

### ISSUE THREAD

**Issue by AhmAli** [SoftverInzenjeringETFSA/SI2014Tim1#103]
Komponenta:
FZaposlenik

commit ID:
e51cebc

Opis problema:
Nije moguće izvršiti modifikaciju sastavnice.

![image](https://cloud.githubusercontent.com/assets/6852893/7898695/3f2fb7ca-0708-11e5-95c1-0672e5d0ad9e.png)

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju 
2. Ulogovati se kao korisnik
3. Odabrati Sastavnice
4. Kreirati novu sastavnicu
5.Odabrati novo kreiranu sastavnicu sa liste 
6. Odabrati opciju modifikuj
7.Dodati nove proizvode u sastavnicu
8. kliknuti na Modifikuj za spremanje promjena

Dobijeni rezultat:
Nije moguće modificirati sastavnicu

Očekivani rezultat:
Modifikacija sastavnice

**Comment by CSharpQueen** [comment]
Isto kao #62
