### ISSUE TITLE
Dugme Nazad ne radi

### ISSUE THREAD

**Issue by akadrispahic** [SoftverInzenjeringETFSA/SI2014Tim1#104]
Komponenta: FZaposlenik
Commit :
e51cebc

Opis problema:
Kada se klikne dugme Nazad, ne desi se ništa

Koraci za reprodukciju:
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara zaposleniku (npr Korisničko ime : prviradnik; šifra : prviradnik)
2.Otvoriti polje skladište
3.Selektovati red, tj. materijal koji želimo modifikovati
4. Odabrati dugme Modifikuj
5. Izmjena nekih od parametara u formi Modifikacija materijala/poluproizvoda

Dobijeni Rezultati
![78](https://cloud.githubusercontent.com/assets/11389876/7898713/eb53cb68-0708-11e5-9da9-2ad15fd51fef.jpg)

Očekivani rezultati:
Da se vratim na prethodnu formu

**Comment by CSharpQueen** [comment]
Isto kao #102
