### ISSUE TITLE
Modifikacija materijala u skladištu - u glavnoj formi za modifikaciju ne postoji button za spremanje promjena

### ISSUE THREAD

**Issue by AhmAli** [SoftverInzenjeringETFSA/SI2014Tim1#105]
Komponenta:
FZaposlenik

commit ID:
e51cebc

Opis problema:
Nije moguće izvršiti modifikaciju  materijala jer ne postoji button za spremanje promjena u glavnoj formi.

![image](https://cloud.githubusercontent.com/assets/6852893/7898719/18a5bb8a-0709-11e5-8c93-54fc8155e59b.png)

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju 
2. Ulogovati se kao korisnik
3. Odabrati Skladište
4.Odabrati materijal za modifikaciju

Dobijeni rezultat:
Forma u kojoj ne postoji button za spremanje promjena nakon modifikacije

Očekivani rezultat:
Spremanje modifikacije putem buttona za spremanje

**Comment by CSharpQueen** [comment]
Isto kao #102
