### ISSUE TITLE
Prikaz klijenata

### ISSUE THREAD

**Issue by akadrispahic** [SoftverInzenjeringETFSA/SI2014Tim1#106]
Komponenta: FMenadzer

Commit : 
e51cebc

Opis problema:
Prilikom odabira dugmeta Prikaži, iako su se odabrali način soritranja (po imenu) i pretrage (po imenu) ništa se ne desi

Koraci za reprodukciju:
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom za menadzera (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.Odabrati Klijenti
3. Odabrati na sortiraj po : imenu
4.Odabrati na pretraži po : imenu
5 Unijela tekst : KlijentPrvi
6.Odabrati dugme Prikaži

Dobijeni rezultati:
![87](https://cloud.githubusercontent.com/assets/11389876/7898746/3e9776c0-070a-11e5-892f-c96b686fa705.jpg)

Očekivani rezultati:

Otvaranje neke druge forme na kojoj bi se prikazale svi klijenti ili da u tabeli ispod budu prikazani oni klijenti koji odgovaraju prema parametrima sortiranja i pretrage, ili Izbaciti ErrorProvider sa porukom koja objašnjava u čemu je problem.

**Comment by CSharpQueen** [comment]
Isto kao #36 i #37
