### ISSUE TITLE
Dodavanje novoga materijala u skladištu bez naziva i serijskog broja

### ISSUE THREAD

**Issue by AhmAli** [SoftverInzenjeringETFSA/SI2014Tim1#107]
Komponenta:
FZaposlenik

commit ID:
e51cebc

Opis problema:
Dodavanje novog materijala u skladištu moguće bez  unosa naziva i serijskog broja materijala.

image
![image](https://cloud.githubusercontent.com/assets/6852893/7898750/52a2c32c-070a-11e5-852e-4a37178e7b10.png)

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju 
2. Ulogovati se kao korisnik
3. Odabrati Skladište
4. Odabrati Unos
5. Kliknuti na Dodaj bez unosa naziva materijala i serijskog broja

Dobijeni rezultat:
Kreiran materijal bez naziva i serijskog broja

Očekivani rezultat:
Materijal sa potpunim podacima.

**Comment by CSharpQueen** [comment]
Isto kao #64
