### ISSUE TITLE
Brisanje korisnika

### ISSUE THREAD

**Issue by akadrispahic** [SoftverInzenjeringETFSA/SI2014Tim1#108]
Komponenta: FMenadzer

Commit : 
e51cebc

Opis problema:
Selektovanog zaposlenika nije moguce izbrisati. Međutim kada sam dodala novog menadzera, njega sam uspjela izbrisati

Koraci za reprodukciju:
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom za menadzera (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.Odabrati dugme Korisnici
3. Selektovati radnika kojeg želite izbrisati
4.Odabrati dugme Obriši

Dobijeni Rezultati:
![999](https://cloud.githubusercontent.com/assets/11389876/7898787/23d15a02-070c-11e5-980a-3d3cd7553f39.jpg)

ovo je kada sam uspjela izbrisati menadzera 
![pokit_724f8e7a7417bca359aff85b66ebe89a](https://cloud.githubusercontent.com/assets/11389876/7898789/4d8368d6-070c-11e5-959f-37ba24edc78b.jpg)

Očekivani rezultati:

Da uspješno izbriše menadžera.

**Comment by CSharpQueen** [comment]
Isto kao #98
