### ISSUE TITLE
Kreiranje novog korisnika, JMBG error iako je uneseno 13 znamenki

### ISSUE THREAD

**Issue by AhmAli** [SoftverInzenjeringETFSA/SI2014Tim1#109]
Komponenta :
Forma "Korisnici" i "Kreiraj korisnika"

Commit : 
e51cebc

Opis problema:
Greška pri unosu JMBG i dalje prisutna iako je uneseno 13 znamenki.

![image](https://cloud.githubusercontent.com/assets/6852893/7898781/e61304d6-070b-11e5-9310-075d944710c1.png)

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju 
2. Ulogovati se kao menadzer
3. Odabrati Korisnike
4. Odabrati Unos novog korisnika
5. Unijeti korektan JMBG

Dobijeni rezultat:
Greška o ne validnom JMBG

Očekivani rezultat:
Validan JMBG i nastavak popunjavanja polja za dodavanje.

**Comment by CSharpQueen** [comment]
Da bi JMBG bio validan nije dovoljno da zadovolji samo unos od 13 cifara. Radjeno je na tome da validacija JMBG-a bude takva da omoguci samo unos sto vise validnih JMBG-a.
