### ISSUE TITLE
Dugme Nazad ne radi

### ISSUE THREAD

**Issue by akadrispahic** [SoftverInzenjeringETFSA/SI2014Tim1#110]
Komponenta: FMenadzer

Commit : 
e51cebc

Opis problema:
Nakon odabira dugmeta Nazad, ne vraća u prethodnu formu.

Koraci za reprodukciju:
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom za menadzera (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.Odabrati Sastavnice
3. Selektivati sastavnicu koju želimo pregledati
4.Odabrati dugme Pregledaj
5.Odabrati dugme Nazad

Dobijeni Rezultati:
![nazad](https://cloud.githubusercontent.com/assets/11389876/7898848/c2238d64-070d-11e5-842b-5acb4c96dfa1.jpg)

Očekivani rezultat:
Da se vrati na formu prije

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 154faa45e5b5cd512dbe4f5090bb882a6d140b05
