### ISSUE TITLE
Dugme Obrisi ne radi

### ISSUE THREAD

**Issue by akadrispahic** [SoftverInzenjeringETFSA/SI2014Tim1#111]
Komponenta: FMenadzer

Commit : 
e51cebc

Opis problema:
Nakon odabira dugmeta Obrisi, ne vraća niti obavijesti o uspješnom brisanju, niti o eventulanoj grešci.

Koraci za reprodukciju:
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom za menadzera (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.Odabrati Sastavnice
3. Selektivati sastavnicu koju želimo pregledati
4.Odabrati dugme Obriši
5.Odabrati dugme Obriši

Dobijeni Rezultati:
![obrisi](https://cloud.githubusercontent.com/assets/11389876/7898886/ba38c76c-070e-11e5-8aae-49199f5ee8b9.jpg)

Očekivani rezultati:

Obavijest o uspješnom brisanju ili da izbaciti ErrorProvider sa porukom koja objašnjava u čemu je problem.

**Comment by CSharpQueen** [comment]
Isto kao #62
