### ISSUE TITLE
Modifikacija sastavnice (prijavljen kao zaposlenik)

### ISSUE THREAD

**Issue by farisodobasic** [SoftverInzenjeringETFSA/SI2014Tim1#116]
Komponenta : 
Modifikovanje postojeće sastavnice (FSastavnicaDM.java)

Commit : 
9af387259a7194bac04a14c9104305b45a311b8f

Opis problema : 
Nakon što se izabere željena sastavnica iz tabele "Pregled/odabit sastavnice" i odabere dugme "Modifikuj" u novootvorenoj formi nakon izmjena i odabira dugmeta "Modifikuj" ništa se ne dešava. Nikakva poruka niti zatvarnje forme. Također u tabeli se ne promjeni nikakav podatak vezan za modifikovanu sastavnicu.

Koraci za reprduciranje problema : 
1. Pokrenuti desktop aplikaciju "BOM" bilo kroz login formu (login.java) ili direktno pokrenuti FMenadzer.java formu.
2.Prijaviti se kao zaposlenik (npr username : privradnik, pass : privradnik)
3.Ovoriti tab "Sastavnice"
4.Odabati neku od sastavnica iz tabele "Pregled/odabir sastavnice"
5.Odabrati dugme"Modifikuj"
6.Izvršiti određene promjene (npr odabrati dugme "Dodaj stavku")
7.Odabrati dugme "Modifikuj"

Dobijeni rezultat : 
Nikakva promjena u odnosu na stanje prije odabira dugmeta "Modifikuj"  :
![13](https://cloud.githubusercontent.com/assets/11445946/7899481/7acf1f02-0724-11e5-9018-2c923b79c68a.png)

Očekivani izlaz : 
Određena poruka o uspješnoj modifikaciji ili eventualnoj greški.
Promjena nekog od podataka u tabeli ,vezanog za tu sastavnicu (npr Cijena)

**Comment by benjaminBeganovic** [comment]
ispravljeno
