### ISSUE TITLE
Dodavanje materijala/poluprizvoda - naziv se generiše sam, svaki put isto

### ISSUE THREAD

**Issue by farisodobasic** [SoftverInzenjeringETFSA/SI2014Tim1#118]
Komponenta :
Unos materijala/poluproizvoda (prijavljen kao korisnik) - FMaterijalDMPB.java

Commit : 
a4d5208f2f1c6f8e68b9edff274015c0dd8fd196

Koraci za reproduciranje problema : 
1. Pokrenuti desktop aplikaciju "BOM" bilo kroz login formu (login.java) ili direktno pokrenuti FMenadzer.java formu.
2.Prijaviti se kao zaposlenik (npr username : privradnik, pass : privradnik)
3.Odabrati tab "Skladište"
4.U groupboxu "Novi materijal/poluproizvo" odabrati dugme "Unesi"
5.Popuniti ispravno sva polja
6.Odabrati dugme "Unesi"

Dobijeni rezultat :
U tabeli se dodaje novi materijal/poluproizvod  s tim što mu je ime stalno isto i automatski generisano, bez obzira šta smo unijeli kao ime pri kreiranju  :
![16](https://cloud.githubusercontent.com/assets/11445946/7899542/387d9400-0727-11e5-86f6-f241592722b8.png)
![15](https://cloud.githubusercontent.com/assets/11445946/7899544/3b3f73ac-0727-11e5-98f7-df145249e867.png)

Očekivani rezultat : 
Očekuje se da se u tabeli ispiše ime koje je zaposlenik unio.

**Comment by CSharpQueen** [comment]
Ispravljeno, izmijenjena polja čije se vrijednosti upisuju, commit: a33c2515b0117d7d215c4a9a66aa9d7585dc591e.
