### ISSUE TITLE
Dupliranje u narudzbenici

### ISSUE THREAD

**Issue by kiselitza** [SoftverInzenjeringETFSA/SI2014Tim1#33]
Komponenta:
Glavna forma (FManadzer.java)

commit ID:
f8fe3c80c2c27cc4834445035dd220188a24db7a

Opis problema:
Tabela za prikaz narudžbenica ne radi ispravno.

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM" bilo kroz login formu (login.java) ili direktno pokrenuti FManadzer.java formu.

Dobijeni rezultat:
- Na formi koja se prikaže u tabeli pregleda narudžbenica prikaže duplo sve narudžbe što je vidljivo i na screenshotu ( http://prntscr.com/79mxfk ) iako se u bazi pomenute narudžbenice nalaze upisano samo jednom ( http://prntscr.com/79n4qp ).

Očekivani rezultat:
- Očekuje se dobiveni prikaz bez dupliranih redova u tabeli.

**Comment by zlatancilic** [comment]
Popravljeno
