### ISSUE TITLE
Narudzbenica sortiranje

### ISSUE THREAD

**Issue by kiselitza** [SoftverInzenjeringETFSA/SI2014Tim1#35]
Komponenta:
Glavna forma (FMenadzer.java)

commit ID:
f8fe3c8

Opis problema:
Sortiranje narudžbenica ne radi ispravno.

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM" bilo kroz login formu (login.java) ili direktno pokrenuti FManadzer.java formu.
2. Na aktivnom tabu Narudžbenice odabrati kriterij sortiranja.
3. Kliknuti na dugme Prikaži.

Dobijeni rezultat:
-    Na formi koja se prikaže u tabeli pregleda narudžbenica prikaže duplo sve narudžbe što je vidljivo i na screenshotu ( http://prntscr.com/79q37w ).

Očekivani rezultat:
-    Očekuje se prikaz narudžbenica koji zadovoljavaju kriterij sortiranja.

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 267e2da3a4802376a2ebc2b2b6448c14b18c7e84
