### ISSUE TITLE
Klijenti sortiranje

### ISSUE THREAD

**Issue by kiselitza** [SoftverInzenjeringETFSA/SI2014Tim1#37]
Komponenta:
Glavna forma (FMenadzer.java)

commit ID:
f8fe3c8

Opis problema:
Sortiranje klijenata ne radi ispravno.

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM" bilo kroz login formu (login.java) ili direktno pokrenuti FMenadzer.java formu.
2. Kliknuti na tab Klijenti.
3. Na aktivnom tabu Klijenti odabrati kriterij sortiranja.
4. Kliknuti na dugme Prikaži.

Dobijeni rezultat:
-    Na formi koja se prikaže u tabeli pregleda klijenata prikaže sve klijente što je vidljivo i na screenshotu ( http://prntscr.com/79q7hl ).

Očekivani rezultat:
-    Očekuje se prikaz klijenata koji zadovoljavaju kriterij sortiranja.

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 267e2da3a4802376a2ebc2b2b6448c14b18c7e84
