### ISSUE TITLE
Materijali pretraga

### ISSUE THREAD

**Issue by kiselitza** [SoftverInzenjeringETFSA/SI2014Tim1#40]
Komponenta:
Glavna forma (FMenadzer.java)

commit ID:
f8fe3c8

Opis problema:
Pretraživanje materijala ne radi ispravno.

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM" bilo kroz login formu (login.java) ili direktno pokrenuti FMenadzer.java formu.
2. Kliknuti na tab Skladište.
3. Na aktivnom tabu Skladište odabrati kriterij pretrage.
4. Popuniti polje za pretragu podacima
5. Kliknuti na dugme Prikaži.

Dobijeni rezultat:
-    Na formi koja se prikaže u tabeli pregleda materijala prikaže sve sastavnice što je vidljivo i na screenshotu ( http://prntscr.com/79qit0 ).

Očekivani rezultat:
-    Očekuje se prikaz materijala koji zadovoljavaju kriterij pretrage.

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 267e2da3a4802376a2ebc2b2b6448c14b18c7e84
