### ISSUE TITLE
Pogresni kriteriji pretrage materijala ('ime' i 'prezime')

### ISSUE THREAD

**Issue by kiselitza** [SoftverInzenjeringETFSA/SI2014Tim1#42]
Komponenta:
Glavna forma (FMenadzer.java)

commit ID:
f8fe3c8

Opis problema:
Pretraživanje materijala omogućava izbor kriterija 'ime' i 'prezime' što nisu elementi klase Materijal.java.

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM" bilo kroz login formu (login.java) ili direktno pokrenuti FMenadzer.java formu.
2. Kliknuti na tab Skladište.
3. Na aktivnom tabu Skladište odabrati kriterij pretrage.

Dobijeni rezultat:
-    Na formi koja se prikaže u tabeli pregleda materijala prikaže sve sastavnice što je vidljivo i na screenshotu ( http://prntscr.com/79qjfy ).

Očekivani rezultat:
-    Očekuje se mogućnost izbora adekvatnih elemenata za pretragu.

**Comment by CSharpQueen** [comment]
Ispravljeno, commit e51cebcc647070bd7daad204320a711af9a1c63d
