### ISSUE TITLE
Modificiranje materijala - unos praznih polja

### ISSUE THREAD

**Issue by kiselitza** [SoftverInzenjeringETFSA/SI2014Tim1#44]
Komponenta:
Forma za modificiranje materijala (FMaterijalDMPB.java)

commit ID:
f8fe3c8

Opis problema:
Modificiranje materijala omogućava izbor praznog stringa za Serijski broj, tip, te naziv materijala

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM" bilo kroz login formu (login.java) ili direktno pokrenuti FMenadzer.java formu.
2. Kliknuti na tab Skladište.
3. Na aktivnom tabu Skladište iz tabele odabrati neki materijal.
4. Kliknuti na dugme modifikuj.
5. Na otvorenom prozoru odabrati ponuđene opcije za modifikaciju materijala.

Dobijeni rezultat:
-    Na formi koja se prikaže, materijal poprima modificirane vrijednosti iako su prazne što je vidljivo i na screenshotu ( http://prntscr.com/79qrtj ) a to se reflektuje i u bazi.

Očekivani rezultat:
-    Očekuje se validacija navedena u SRS dokumentu da sve vrijednosti moraju biti unesene.

**Comment by CSharpQueen** [comment]
Ispravljeno, commit: e51cebcc647070bd7daad204320a711af9a1c63d .
