### ISSUE TITLE
Dodavanje korisnika validacija 'ime'

### ISSUE THREAD

**Issue by kiselitza** [SoftverInzenjeringETFSA/SI2014Tim1#45]
Komponenta:
Forma za dodavanje korisnika (FKorisnikDMPB.java)

commit ID:
dd7221a70acb2d6b68acf6887ddcbf3c91be7de7

Opis problema:
Kreiranje korisnika dozvoljava unos polja 'ime' korisnika malim početnim slovom kao i sva ostala slova velikim.

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM" bilo kroz login formu (login.java) ili direktno pokrenuti FMenadzer.java formu.
2. Kliknuti na dugme Korisnici.
3. Na otvorenom prozoru Korisnici kliknuti dugme Kreiraj.
4. Na otvorenom prozoru Kreiranje korisnika unijeti podatke.
5. U polje Ime unijeti bilo koji niz alpha karaktera lower ili upper case ili kombinovano
6. Kliknuti na dugme Kreiraj.

Dobijeni rezultat:
-    Na formi koja se prikaže, nema potvrde o greški (http://prntscr.com/79rbio).

Očekivani rezultat:
-    Očekuje se validacija polja imena i prezimena kako bi se izbjegla duplikacija korisnika.

**Comment by CSharpQueen** [comment]
Ispravljeno tako da je dozvoljen unos navedenih vrijednosti u polja, s tim da se prije smjestanja u bazu izvrsi konverzija podataka, commit: f655a24bf32ef65297e2bc7f26beb67688515240.
Ime i prezime nisu jedinstveni, tako da korisnici sa istim imenom i prezimenom mogu postojati, pri cemu se razlikuju po drugim parametrima.
