### ISSUE TITLE
Dodavanje korisnika validacija 'prezime'

### ISSUE THREAD

**Issue by kiselitza** [SoftverInzenjeringETFSA/SI2014Tim1#46]
Komponenta:
Forma za dodavanje korisnika (FKorisnikDMPB.java)

commit ID:
dd7221a70acb2d6b68acf6887ddcbf3c91be7de7

Opis problema:
Kreiranje korisnika dozvoljava unos polja 'prezime' korisnika malim početnim slovom kao i sva ostala slova velikim.

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM" bilo kroz login formu (login.java) ili direktno pokrenuti FMenadzer.java formu.
2. Kliknuti na dugme Korisnici.
3. Na otvorenom prozoru Korisnici kliknuti dugme Kreiraj.
4. Na otvorenom prozoru Kreiranje korisnika unijeti podatke.
5. U polje Prezime unijeti bilo koji niz alpha karaktera lower ili upper case ili kombinovano
6. Kliknuti na dugme Kreiraj.

Dobijeni rezultat:
-    Na formi koja se prikaže, nema potvrde o greški ( http://prntscr.com/79rbut ).

Očekivani rezultat:
-    Očekuje se validacija polja prezimena koristeći adekvatan regex (Prvo slovo prezimena velikim, ostala slova malim imenom)

**Comment by zlatancilic** [comment]
Nisam uspio shvatiti, da li je ovdje problem to što je moguće unijeti prezime na način da je nebitno je li počinje/završava malim/velikim slovom, ili je problem mogućnost unošenja istih korisnika?

**Comment by zlatancilic** [comment]
Koristi se ista metoda kao i za validaciju imena tako da je ovo duplikat. #45

**Comment by kiselitza** [comment]
Editovan očekivani rezultat. :+1:
