### ISSUE TITLE
Dodavanje klijenata validacija 'prezime'

### ISSUE THREAD

**Issue by kiselitza** [SoftverInzenjeringETFSA/SI2014Tim1#49]
Komponenta:
Forma za dodavanje klijenata (FKlijentDMPB.java)

commit ID:
dd7221a

Opis problema:
Kreiranje korisnika dozvoljava unos polja 'prezime' korisnika malim početnim slovom kao i sva ostala slova velikim.

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM" bilo kroz login formu (login.java) ili direktno pokrenuti FMenadzer.java formu.
2. Kliknuti na tab Klijenti
3. Na otvorenom tabu Klijenti kliknuti dugme Kreiraj.
4. Na otvorenom prozoru Kreiranje klijenta unijeti podatke.
5. U polje Prezime unijeti bilo koji niz alpha karaktera lower ili upper case ili kombinovano
6. Kliknuti na dugme Kreiraj.

Dobijeni rezultat:
-    Na formi koja se prikaže, nema potvrde o greški ( http://prntscr.com/79rkkn ).

Očekivani rezultat:
-    Očekuje se validacija polja prezimena kako bi se izbjegla duplikacija klijenata.

**Comment by zlatancilic** [comment]
Koristi se ista metoda kao i za validaciju imena tako da je ovo duplikat. #45
