### ISSUE TITLE
Menadzer soritranje korisnika

### ISSUE THREAD

**Issue by farisodobasic** [SoftverInzenjeringETFSA/SI2014Tim1#50]
Komponenta : 
Glavna forma za menadzera (FMenadzer.java)

Commit : 
f8fe3c80c2c27cc4834445035dd220188a24db7a

Opis problema : 
Sortiranje korisnika po :  -nazivu
                                       -datumu kreiranja, ne radi
U slučaju da se odabere soritranje po datumu kreiranje i dalje nemamo uvida da je li stvarno tako jer nije nigdje prikazan datum.

Korak za reproduciranje problema :
1. Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara menadzeru (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.U gornjem desno uglu pritisnuti dugme "Korisnici"
3.U novootvorenoj formi u grouboxu "Pretraga" sortiranje mozemo uraditi na 2 nacina : po nazivu, po datumu kreiranju.
4.Odabrati jedan od nacina sortiranja

Dobijeni rezultat : 
Na formi je prikazan tabela u kojoj se nalaze svi korisnici : http://prntscr.com/79rqmg
![1](https://cloud.githubusercontent.com/assets/11445946/7824393/e9c6e8e2-0402-11e5-85d6-a7a121c2b082.png)

Očekivani rezultat : 
Očekuje se da korisnici unutar tabele budu soritrani po odabranom kriteriju.

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: e35e45bbf611896e9cb17d1b7ad6ea2399c71821
