### ISSUE TITLE
Menadzer pretraga korisnika

### ISSUE THREAD

**Issue by farisodobasic** [SoftverInzenjeringETFSA/SI2014Tim1#51]
Komponenta :
Glavna forma za menadzera (FMenadzer.java)

Commit :
f8fe3c8

Opis problema :
Pretraga korisnika po :
-nazivu
-datumu kreiranja, ne radi.

Korak za reproduciranje problema :
1. Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara menadzeru (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.U gornjem desnom uglu pritisnuti dugme "Korisnici"
3.U novootvorenoj formi u grouboxu "Pretraga" pretragu mozemo uraditi na 2 nacina : po nazivu, po datumu kreiranju.
4.Odabrati jedan od nacina pretrage 
5.Pritisnuti dugme "Pretrazi"

Dobijeni rezultat :
Na formi je prikazan tabela u kojoj se nalaze svi korisnici :
![1](https://cloud.githubusercontent.com/assets/11445946/7824499/9936e0de-0403-11e5-9cc7-69fcad3b562d.png)

Očekivani rezultat : 
Da u tabeli budu prikazani korisnici koji su rezultat pretrage. Pored textboxa ispod kriterija pretrage bi trebalo napisati sta treba unijeti.

**Comment by benjaminBeganovic** [comment]
Ispravljneo u komitu: e35e45bbf611896e9cb17d1b7ad6ea2399c71821
