### ISSUE TITLE
Kreiranje korisnika validiranje

### ISSUE THREAD

**Issue by farisodobasic** [SoftverInzenjeringETFSA/SI2014Tim1#52]
Komponenta : 
Forma za dodavanje korisnika (FKorisnikDMPB.java)

Commit : 
dd7221a70acb2d6b68acf6887ddcbf3c91be7de7

Opis problema : 
Prilikom unosa podataka u formu za kreiranje korisnika ukoliko se pod određenim redoslijedom unesu pogrešni podaci (opisano u sljedećoj stavci) errorprovider kao i fokus se pojavljuju na textboxu gdje je predviđeno da se unese korisničko ime dok signralizira da adresa nije u redu.

Koraci za reproduciranje problema : 
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara menadzeru (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.U gornjem desnom uglu pritisnuti dugme "Korisnici"
3.Odabrati dugme "Kreiraj" koje je unutra groupboxa "Novi korisnik"
4.Popuniti ime,prezime,jmbg sa validnim podacima 
5.Nakon popunjenih navedenih podataka pritisnuti dugme "Kreiraj"

Dobijeni rezultat : 
Fokus i errorprovider sa prukom da adresa nije ispravna, sto je donekle tacno, ali na pogresnom mjestu.
![2](https://cloud.githubusercontent.com/assets/11445946/7825060/ebb480dc-0408-11e5-9682-64e44b6bda7e.png)

Očekivani rezultat : 
Očekuje se da se errorprovider i fokus pojave na ispravnom mjestu sa ispravnom porukom (kada već postoje).

**Comment by CSharpQueen** [comment]
Ispravljeno, commit: e51cebcc647070bd7daad204320a711af9a1c63d .
