### ISSUE TITLE
Kreiranje korisnika - odabir tipa pozicije

### ISSUE THREAD

**Issue by farisodobasic** [SoftverInzenjeringETFSA/SI2014Tim1#53]
Komponenta :
Forma za dodavanje korisnika (FKorisnikDMPB.java)

Commit :
dd7221a

Opis problema : 
Prilikom unosa pogrešnih podataka u formu za kreiranje novog korisnika, i pritiskanja dugmeta  "Kreiranja" u comboboxu "Pozicija" tipovi pozicije se poduplavaju. Nakon 3 puta pritisnutog dugmeta "Kreiraj" sa pogrešnim podacima u comboboxu se nalaze 3 puta tipovi pozicije.
U prvoj iteraciji combobox je prazan dok se ne pritisne dugme "Kreiraj".

Koraci za reproduciranje problema : 
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara menadzeru (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.U gornjem desnom uglu pritisnuti dugme "Korisnici"
3.Odabrati dugme "Kreiraj" koje je unutra groupboxa "Novi korisnik"
4.Pritisnuti dugme "Kreiraj" nekoliko puta bilo sa praznim textboxovima ili sa pogresnim podacima
5.Pritisnuti combobox "Pozicija"

Dobijeni rezultati : 
Uvecan broj istih tipova pozicije kao i prazna mjesta između istih, koja se mogu odabrati 
![3](https://cloud.githubusercontent.com/assets/11445946/7825190/1f662434-040a-11e5-81a6-1514827dd236.png)

Očekivani rezultat : 
Broj tipova pozicije bi trebao da ostane isti. (menadzer/zaposlenik)

**Comment by CSharpQueen** [comment]
Ispravljeno, commit: e51cebcc647070bd7daad204320a711af9a1c63d .
