### ISSUE TITLE
Modifikovanje korinsika

### ISSUE THREAD

**Issue by farisodobasic** [SoftverInzenjeringETFSA/SI2014Tim1#54]
Komponenta :
Frame Korisnici (logovan kao menadzer) (FKorisnik.java)

Commit : 
4ff76523f7be38aefcedc2d7f4cd15736080d2e1

Opis problema : 
 Dugme "Modifikuj" unutar groupboxa "Postojeći korisnik" nema nikakvu funkcionalnost.

Koraci za reproduciranje problema : 
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara menadzeru (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.U gornjem desnom uglu pritisnuti dugme "Korisnici"
3.Odabrati nekog od korisnika iz tabele 
4.Pritisnuti dugme "Modifikuj"

Dobijeni rezultati :
Nikakve promjene u odnosu na stanje prije pritska na dugme "Modifikuj"
![4](https://cloud.githubusercontent.com/assets/11445946/7825281/7866e7de-040b-11e5-9aa9-78abe2b0b203.png)

Očekivani rezultat : 
Nakon odabira željenog korisnika iz tabele i pritiska na dugme "Modifikuj" očekivano je otvaranje nove forme (ili panela) sa podacima o korisniku koji je odabran i koje je moguće editovati.

**Comment by CSharpQueen** [comment]
Ispravljeno, po kliku na dugme otvara se forma za modifikovanje odabranog korisnika nakon cega se po potvrdi korisnika novi unos sprema u bazu, commit: f655a24bf32ef65297e2bc7f26beb67688515240.
