### ISSUE TITLE
Pregled sastavnice

### ISSUE THREAD

**Issue by farisodobasic** [SoftverInzenjeringETFSA/SI2014Tim1#55]
Komponenta : 
Pregled sastavnice

Commit : 
f8fe3c80c2c27cc4834445035dd220188a24db7a

Opis problema  :
U formi na kojoj se prikazuje pregled odabrane sastavnice dugme "Nazad" nema nikakvu funkcionalnost.

Koraci za reproduciranje problema  :
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara menadzeru (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.Odabrati tab "Sastavnice"
3.Odabrati jednu od sastavnice iz tabele sastavnica
4.Pritisnuti dugme "Pregledaj"
5.U novootvorenom prozoru pritisnuti dugme "Nazad"

Dobijeni rezultati : 
Nikakva promjena se nije desila, ostali smo na istoj formi : 
![5](https://cloud.githubusercontent.com/assets/11445946/7826342/087ba4e2-0419-11e5-8782-5e8da1ebc74a.png)

Očekivani rezultatI : 
Da se napusti trenutno forma i vrati na početnu formu, kako je definisano u specifikaciji korisničkog interfejsa.

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 154faa45e5b5cd512dbe4f5090bb882a6d140b05
