### ISSUE TITLE
Moguće dodavanje istog korisnika više puta 

### ISSUE THREAD

**Issue by farisodobasic** [SoftverInzenjeringETFSA/SI2014Tim1#56]
Komponenta : 
Forma za dodavanje korisnika (FKorisnikDMPB.java)

Commit : 
dd7221a

Opis problema : 
Putem forme za kreiranje novog korisnika moguće je dodati više korisnika sa istim parametrima koji bi trebali da su jedinstveni (jmbg, korisnicko ime)

Koraci za reproduciranje problema  : 
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara menadzeru (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.U gornjem desnom uglu pritisnuti dugme "Korisnici"
3.Odabrati dugme "Kreiraj" koje je unutra groupboxa "Novi korisnik"
4.Unijeti validne podatke u formu
5.Nekoliko puta pritisnuti dugme "Kreiraj"

Dobijeni rezultati : 
U bazu je dodano više korisnika sa istim podacima (i onim koji bi trebali biti jedinstveni za svakog korisnika).
![6](https://cloud.githubusercontent.com/assets/11445946/7826531/553d015c-041b-11e5-93a5-2e3b9159df99.png)

Očekivani rezultati : 
Očekivana je poruka da takav korisnik već postoji u bazi.

**Comment by CSharpQueen** [comment]
Ispravljeno, JMBG je jedinstven za svakog korisnika. 
Commiti: f655a24bf32ef65297e2bc7f26beb67688515240
425e10758536415ca8e9db226ddbf14fb69e3204.
