### ISSUE TITLE
Modifikovanje postojećeg materijala/poluproizvoda

### ISSUE THREAD

**Issue by farisodobasic** [SoftverInzenjeringETFSA/SI2014Tim1#57]
Komponenta : 
Glavna forma menadžera - tab "Skladište" + forma za modifikovanje materijala/poluproizvoda 

Commit : 
f8fe3c80c2c27cc4834445035dd220188a24db7a

Opis problema : 
Pri modifikaciji odabranog materijala/poluproizvoda u comboboxu "Serijiski broj" postoje prazna mjesta koja je moguće odabrati kao serijiski broj i biće prihvaćeni kao serijski broj i spremljeni u bazu (kao prazno).

Koraci za reproduciranje problema  : 
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara menadzeru (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.Odabri taba "Skladište"
3.Odabir jednog od materijala/poluproizvoda iz tabele
4.Pritisnuti dugme "Modifikuj"
5.U comboboxu "Serijski broj" odabrati jedno od praznih mjesta između postojećih serijskih brojeva
6.Pritisnuti dugme "Modifikuj" da bi se promjene spasile

Dobijeni rezultati : 
Serijski broj modifikovanog materijala/poluproizvoda u bazi je prazan.
![7](https://cloud.githubusercontent.com/assets/11445946/7826640/697b69c2-041d-11e5-87f8-53298c684bee.png)
Screenshot iz baze (tabela "materijal")
![8](https://cloud.githubusercontent.com/assets/11445946/7826654/a98480f8-041d-11e5-8e19-f7c1e21b52de.png)

Očekivani rezultati :
Da ne postoji mogućnost odabira praznog ili poruka o pogrešnim podacima.

**Comment by CSharpQueen** [comment]
Isto kao #44, popravljeno, commit: e51cebcc647070bd7daad204320a711af9a1c63d
