### ISSUE TITLE
Dodavanje sastavnica

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#58]
Komponenta:
FSastavnicaDM

Commit:
e51cebcc647070bd7daad204320a711af9a1c63d

Opis problema:
Moguce je dodati sastavnicu bez prethodnog dodavanja stavke

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Kliknuti na tab Sastavnice.
3. Kliknuti na dugme Kreiraj
4. Na formi koja se otvori kliknuti dugme Kreiraj

Dobijeni rezultat:
Textbox koji kaze da smo uspjesno kreirali sastavnicu (provjerom u bazi ustanovimo da je zaista tako)

Ocekivani rezultat:
Niste dodali stavku

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 154faa45e5b5cd512dbe4f5090bb882a6d140b05
