### ISSUE TITLE
Dodavanje sastavnica, tabela

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#59]
Komponenta:
FSastavnicaDM

Commit:
e51cebcc647070bd7daad204320a711af9a1c63d

Opis problema:
Moguce je rucno mijenjati podatke u tabeli, te nakon sto sve podatke izbrisemo, onemoguceno brisanje tog reda iz tabele

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Kliknuti na tab Sastavnice.
3. Kliknuti na dugme Kreiraj
4. Na formi koja se otvori kliknuti dugme Dodaj stavku
5. Izbrisati sve podatke iz jednog reda tabele
6. Selektovati red
7. Kliknuti Izbaci stavku

Dobijeni rezultat:
Nista (ne moze se izbrisati): http://pokit.org/get/?d28861b6c87324a36431911c842eb4d5.jpg

Ocekivani rezultat:
Obrisan red iz tabele

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 154faa45e5b5cd512dbe4f5090bb882a6d140b05
