### ISSUE TITLE
Dodavanje sastavnica, ukupna cijena

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#60]
Komponenta:
FSastavnicaDM

Commit:
e51cebcc647070bd7daad204320a711af9a1c63d

Opis problema:
Ukupna cijena se povecava iako stavka nije dodana

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Kliknuti na tab Sastavnice.
3. Kliknuti na dugme Kreiraj
4. Unijeti nevalidne podatke (npr naziv proizvoda)
5. Kliknuti Dodaj stavku

Dobijeni rezultat:
Ukupna cijena raste: http://pokit.org/get/?dd7b01a22e123c658bb8302a09df4ed6.jpg

Ocekivani rezultat:
Cijena ostaje ista (jer nije dodana u tabelu stavka zbog neispravnih podataka)

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 154faa45e5b5cd512dbe4f5090bb882a6d140b05
