### ISSUE TITLE
Dodavanje sastavnica, serijski broj

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#61]
Komponenta:
FSastavnicaDM

Commit:
e51cebcc647070bd7daad204320a711af9a1c63d

Opis problema:
Ukupna cijena se povecava iako stavka nije dodana

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Kliknuti na tab Sastavnice.
3. Kliknuti na dugme Kreiraj
4. Unijeti nevalidne podatke za serijski broj
5. Kliknuti Dodaj stavku
6. Kliknuti Kreiraj

Dobijeni rezultat:
Serijski broj moze biti nesto sto nema smisla, npr: http://pokit.org/get/?8c57c01a63e056c13d258be565b4012b.jpg

Ocekivani rezultat:
Serijski broj koji pocinje sa S (sudeci po ostalim serijskim brojevima u bazi)

**Comment by zlatancilic** [comment]
@zloco Na c2 pise da se ne uzimaju u obzir bugovi za svako pojedinacno polje, nego samo u pogledju klase. Ovo se koliko vidim odnosi na istu klasu kao i  #60

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 154faa45e5b5cd512dbe4f5090bb882a6d140b05
