### ISSUE TITLE
Pregledaj, obrisi, modifikuj postojecu sastavnicu

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#62]
Komponenta:
FZaposlenik

Commit:
e51cebcc647070bd7daad204320a711af9a1c63d

Opis problema:
Dugmad pregledaj, obrisi, modifikuj nemaju funkciju nikakvu

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Kliknuti na tab Sastavnice.
3. Kliknuti na dugmad modifikuj, obrisi, pregledaj

Dobijeni rezultat:
Nista: http://pokit.org/get/?0fef89d3576e05dba2693000d5695ed2.jpg

Ocekivani rezultat:
Da se otvore neke nove forme

**Comment by zlatancilic** [comment]
Ovo će trebati detaljnije provjeriti, ne dešava se stalno, nego povremeno.

**Comment by benjaminBeganovic** [comment]
ispravljeno u komitu: 154faa45e5b5cd512dbe4f5090bb882a6d140b05
