### ISSUE TITLE
Unos materijala/poluproizvoda

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#63]
Komponenta:
FMaterijalDMPB

Commit:
e51cebc

Opis problema:
U comboboxu se prikazuju materijali umjesto tip (proizvod/poluproizvod)

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Logovati se kao Zaposlenik
3. Kliknuti na tab Skladiste
4. Kliknuti na dugme Unesi
5. Izabrati npr materijal M55 u comboboxu

Dobijeni rezultat:
Lista svih materijala: http://pokit.org/get/?436748d1abd710ecd38e40d97b0c5c9d.jpg

Ocekivani rezultat:
Da prikaze tip (proizvod/poluproizvod)

**Comment by zlatancilic** [comment]
@zloco trebalo bi pogledati u bazu koju imaš lokalno, moguće da imaš unesenih nevalidnih vrijednosti u tabeli iz koje se ovo povlači. Ovo je testirano na svježoj bazi(koja je poslana svim testerima) i niko drugi nije imao ovaj issue. Zasad, označit ću kao invalid.

**Comment by zloco** [comment]
@zlatancilic ja sam importovala onu bazu koju si mi ti poslao, jedino ako ste poslije toga mijenjali bazu ili nesto, posalji mi pa da importujem novu

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 866c50776e937bf40a28cef41a6897c8aa6585e5

**Comment by nerminaagovic** [comment]
Ispravljeno, commit: a4d5208f2f1c6f8e68b9edff274015c0dd8fd196.
