### ISSUE TITLE
Unos materijala/poluproizvoda, bez podataka

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#64]
Komponenta:
FMaterijalDMPB

Commit:
e51cebc

Opis problema:
Moguce je napraviti materijal bez ijednog unesenog podatka

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Kliknuti na tab Skladiste
3. Kliknuti na dugme Unesi
4. Na novoj formi kliknuti dugme Unesi

Dobijeni rezultat:
Dodan novi materijal, bez ikakvih parametara: http://pokit.org/get/img/24bbf2d3415b8849eb5f7923648831bc.jpg

Ocekivani rezultat:
Onemoguceno dodavanje materijala

**Comment by CSharpQueen** [comment]
Ispravljeno, izvršena validacija polja, commit: a33c2515b0117d7d215c4a9a66aa9d7585dc591e.
