### ISSUE TITLE
Dodavanje narudzbenice, serijski broj

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#65]
Komponenta:
FNarudzbenicaD

Commit:
e51cebc

Opis problema:
Moguce je kreirati narudzbenicu sa neispravnim serijskim brojem

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Logovati se kao menadzer
3. Kliknuti na tab Narudzbenice
4. Kliknuti na dugme Kreiraj
5. Unijeti serijski broj npr -200
6. Na novoj formi kliknuti dugme Kreiraj

Dobijeni rezultat:
Dodan novi materijal, sa nevalidnim serijskim brojem: http://pokit.org/get/img/c615172a8612c7edb93f077c54a49782.jpg

Ocekivani rezultat:
Onemoguceno dodavanje narudzbenice

**Comment by zlatancilic** [comment]
Opis koraka nije u skladu sa priloženom slikom. Nigdje u SRS-u ne piše da će serijski broj biti tačno određenog formata, stoga samtram da je ovako formulisan issue nevalidan. Zasad ću staviti taj label, podložno je promjenama ukoliko se ustanovi da je trebaklo preformulisati issue.

**Comment by ArnelaBesic** [comment]
Ispravljeno da se serijski broj može unijeti samo u formatu [a-z][0-9]
Commit: 46993899b43eeaeae1f9543c239fa50f7f59121f
