### ISSUE TITLE
Dodavanje narudzbenice, bez proizvoda

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#66]
Komponenta:
FNarudzbenicaD

Commit:
e51cebc

Opis problema:
Moguce je kreirati narudzbenicu bez ijednog proizvoda

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Logovati se kao menadzer
2. Kliknuti na tab Narudzbenice
3. Kliknuti na dugme Kreiraj
4. Na novoj formi kliknuti dugme Kreiraj

Dobijeni rezultat:
Dodan novi materijal, bez proizvoda: http://pokit.org/get/img/c615172a8612c7edb93f077c54a49782.jpg

Ocekivani rezultat:
Onemoguceno dodavanje narudzbenice

**Comment by ArnelaBesic** [comment]
Ispravljeno dodavanjem if uslova za broj redova u tabeli. Ako je manji od 1, prijavit će se greška.
Commit: 4a3de3d5a2a377be2c3883ed8505a4b378a4f5c9
