### ISSUE TITLE
Dodavanje narudzbenice, tabela

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#67]
Komponenta:
FNarudzbenicaD

Commit:
e51cebc

Opis problema:
Moguce je rucno mijenjati podatke u tabeli, te nakon sto sve podatke izbrisemo, onemoguceno brisanje tog reda iz tabele

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Logovati se kao menadzer
2. Kliknuti na tab Narudzbenice
3. Kliknuti na dugme Kreiraj
4. Na formi koja se otvori kliknuti dugme Dodaj proizvod
5. Izbrisati sve podatke iz jednog reda tabele
6. Selektovati red
7. Kliknuti Izbaci proizvod

Dobijeni rezultat:
Nista (ne moze se izbrisati): http://pokit.org/get/?3516749cb01045ab273955ff0daa260d.jpg

Ocekivani rezultat:
Obrisan red iz tabele

**Comment by ArnelaBesic** [comment]
Ispravljeno tako što je onemogućeno mijenjati podatke u tabeli.
Commit :  4a3de3d5a2a377be2c3883ed8505a4b378a4f5c9
