### ISSUE TITLE
Kreiranje klijenta, validacija adrese

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#68]
Komponenta:
FKlijentDMPB

Commit:
e51cebc

Opis problema:
Nije uradjena validacija za adresu (moguce je unijeti bilo sta)

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Logovati se kao menadzer
2. Kliknuti na tab Klijenti
3. Kliknuti na dugme Kreiraj
4. Na novoj formi kliknuti dugme Kreiraj

Dobijeni rezultat:
Mogu se unijeti bilo kakvi znakovi za adresu: http://pokit.org/get/img/525030c8aaa82c647c9863c6a583b80b.jpg

Ocekivani rezultat:
Samo slova, brojevi i prazna mjesta (eventualno crtica -)

**Comment by ArnelaBesic** [comment]
Omogućeno unošenje adresa koje se sastoje od kombinacije slovo, brojevi i razmaci promjenom regex-a koji se koristio za prijašnju validaciju.
Onemogućeno slanje praznog telefonskog broja testiranjem sadržaja string koji se šalje da li se sastoji samo od maske.
Commit :75a226d3075d6fdc069aa2d12f871df97ddf2d94
