### ISSUE TITLE
Kreiranje klijenta, validacija telefona

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#69]
Komponenta:
FKlijentDMPB

Commit:
e51cebc

Opis problema:
Ako se ne unese broj telefona, prikaze se kao +_________ u tabeli/bazi

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Logovati se kao menadzer
2. Kliknuti na tab Klijenti
3. Kliknuti na dugme Kreiraj
4. Na novoj formi kliknuti dugme Kreiraj

Dobijeni rezultat:
Telefon bez ijednog broja:
http://pokit.org/get/?7a620635701ba2a55a41069f4147be3d.jpg

Ocekivani rezultat:
Zahtijevanje unosa broja telefona prije kreiranja klijenta

**Comment by zlatancilic** [comment]
Na istoj klasi kao #68 tako da je duplicate
