### ISSUE TITLE
Kreiranje korisnika, jmbg validacija

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#70]
Komponenta:
FKorisnikDMPB

Commit:
e51cebc

Opis problema:
Unesen ispravan jmbg, errorprovider ne priznaje, samim tim se ne moze kreirati korisnik

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Logovati se kao menadzer
2. Kliknuti na dugme Korisnici
3. Kliknuti na dugme Kreiraj
4. Na novoj formi unijeti jmbg

Dobijeni rezultat:
Ne prihvata (moj) jmbg:
http://pokit.org/get/img/66b8bd63bd9e8b393ebf11ff8b16d050.jpg

Ocekivani rezultat:
Nestanak errorprovidera

**Comment by CSharpQueen** [comment]
Uradjena je takva validacija koja prolazi za veliki broj validnih JMBG-ova.
Ipak, nije tako dobra da ih podrzava sve.

**Comment by zloco** [comment]
ne znam, ja sam isprobavala i jmbg-ove iz vase baze i nisu prolazili :O

**Comment by zlatancilic** [comment]
Baza je pravljena odvojeno skroz i nije zeto u obzir ovo. Bit će popravljeno.
