### ISSUE TITLE
Pregled materijala/poluproizvoda, selektovan red bez opisa

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#71]
Komponenta:
FMaterijalDMBP

Commit:
e51cebc

Opis problema:
Kada se selektuje u tabeli red sa opisom i klikne na Pregledaj, ne desi se nista, a kad se selektuje red bez opisa iz tabele i klikne dugme Pregledaj, otvori se nova forma bez ikakvih podataka

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Logovati se kao menadzer
2. Kliknuti na tab Skladista
3. Izabrati red bez opisa u tabeli
4. Kliknuti dugme Pregledaj

Dobijeni rezultat:
Forma bez parametara:
http://pokit.org/get/img/c58165345277481d39fd9727cdc68562.jpg

Ocekivani rezultat:
Forma popunjena parametrima

**Comment by zlatancilic** [comment]
@zloco trebalo bi pogledati u bazu koju imaš lokalno, moguće da imaš unesenih nevalidnih vrijednosti u tabeli iz koje se ovo povlači. Ovo je testirano na svježoj bazi(koja je poslana svim testerima) i niko drugi nije imao ovaj issue. Zasad, označit ću kao invalid.

**Comment by benjaminBeganovic** [comment]
Nije baza bila dobra
