### ISSUE TITLE
Pregledanje korisnika - polje šifra

### ISSUE THREAD

**Issue by kiselitza** [SoftverInzenjeringETFSA/SI2014Tim1#72]
Komponenta:
Forma za pregledanje korisnika (FKorisnikDMPB.java)

commit ID:
e51cebcc647070bd7daad204320a711af9a1c63d

Opis problema:
Pregledanje korisnika dozvoljava unos polja šifra (iako se isti ne reflektuje na bazu).

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM" bilo kroz login formu (login.java) ili direktno pokrenuti FMenadzer.java formu.
2. Kliknuti na dugme Korisnici.
3. Na otvorenom prozoru Korisnici odabrati korisnika.
4. Na otvorenom prozoru Korisnici kliknuti na dugme Pregledaj.

Dobijeni rezultat:
-    Na formi koja se prikaže, editabilno je polje šifra ( http://prntscr.com/7aoonk ).

Očekivani rezultat:
-    Očekuje se da pomenuto polje ne postoji na formi ili sadrži heširanu šifru (i uz to nije editabilno).

**Comment by CSharpQueen** [comment]
Popravljeno, polje onemoguceno, commit: f655a24bf32ef65297e2bc7f26beb67688515240
