### ISSUE TITLE
Pregledanje sastavnica - polje ukupna vrijednost

### ISSUE THREAD

**Issue by kiselitza** [SoftverInzenjeringETFSA/SI2014Tim1#73]
Komponenta:
Forma za pregledanje sastavnica (FSastavnicaPB.java)

commit ID:
e51cebcc647070bd7daad204320a711af9a1c63d

Opis problema:
Pregledanje sastavnica ne sadrži popunjena sva polja.

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM" bilo kroz login formu (login.java) ili direktno pokrenuti FMenadzer.java formu.
2. Kliknuti na tab Sastavnice.
3. Na otvorenom tabu Sastavnice odabrati sastavnicu.
4. Na istom tabu Sastavnice kliknuti na dugme Pregledaj.

Dobijeni rezultat:
-    Na formi koja se prikaže, polje ukupna vrijednost je prazno ( http://prntscr.com/7aor3d ).

Očekivani rezultat:
-    Očekuje se da pomenuto polje sadrži vrijednost koja odgovara proizvodu KM/h \* h ili odgovarajućoj varijaciji koja je zamišljena prvobitno od strane razvojnog tima.

**Comment by zlatancilic** [comment]
Opis problema nije validan

**Comment by kiselitza** [comment]
Editovan opis, hvala :D

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 154faa45e5b5cd512dbe4f5090bb882a6d140b05
