### ISSUE TITLE
Odjava sa sistema

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#74]
Komponenta:
Login

Commit:
e51cebc

Opis problema:
U SRS-u pise da se pri odjavi sistema treba prikazati poruka o uspjesnoj/neuspjesnoj odjavi:
http://pokit.org/get/?ac15fbed3098e581fa99fbdbd47b4c67.jpg

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Logovati se kao menadzer/zaposlenik
3. Odjaviti se sa sistema

Dobijeni rezultat:
Zatvori se forma

Ocekivani rezultat:
Obavijest o uspjesnoj/neuspjesnoj odjavi

**Comment by zloco** [comment]
izvinite do mene je bilo :D ne mogu izbrisati issue, pa sam ga samo zatvorila

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: c1d9d28b11287d63a5bf0a106f4c1661cfb09aa0
