### ISSUE TITLE
Obavjestavanje o manjku materijala

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#75]
Komponenta:
FMenadzer

Commit:
e51cebc

Opis problema:
U SRS-u je navedeno da se treba pojaviti obavijest u slucaju manjka materijala u skladistu, medjutim dugme za brisanje ne funkcionise, te nema nacina da se testira funkcionalnost provjere manjka materijala

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Logovati se kao menadzer
2. Kliknuti na tab Skladista
3. Kliknuti dugme Prikazi sve
4. Obrisati sve materijale iz tabele (kada se to omoguci)

Dobijeni rezultat:
Trenutno nista

Ocekivani rezultat:
Obavijest o manjku materijala

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 1db198832a125adc9ed03b0b0fc0e2d724083ab3
