### ISSUE TITLE
Brisanje sastavnica od strane zaposlenika, SRS

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#78]
Komponenta:
FZaposlenik

Commit:
e51cebc

Opis problema:
U SRS-u je navedeno sljedece: http://pokit.org/get/img/e45ba571a82d3b720dcecb15b62446b3.jpg
dok u vasoj aplikaciji zaposlenik brise sastavnice

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Logovati se kao zaposlenik
3. Kliknuti na tab Sastavnice
4. Odabrati sastavnicu iz tabele (kad bi vam radilo dugme Prikazi Sve)
3. Kliknuti dugme Obrisi

Dobijeni rezultat:
Obrisana sastavnica

Ocekivani rezultat:
Nemogucnost brisanja sastavnice zbog stepena ovlastenja navedenog u SRSu

**Comment by zlatancilic** [comment]
Odnosi se na istu klasu problema kao #77
