### ISSUE TITLE
Odjava sa sistema 2

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#79]
Komponenta:
FZaposlenik

Commit:
e51cebc

Opis problema:
U SRS-u je navedeno sljedece: http://pokit.org/get/img/8d5ffe74f735b935eb2bef3f6c2b34af.jpg
a ovo se ne izvrsi, ne otvara se login forma opet, vec se samo izlazi iz aplikacije

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Logovati se kao zaposlenik
3. Odjaviti se sa sistema

Dobijeni rezultat:
Izlazak iz aplikacije

Ocekivani rezultat:
Otvaranje login forme

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 1db198832a125adc9ed03b0b0fc0e2d724083ab3
