### ISSUE TITLE
Kreiranje sastavnice, otpad SRS

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#81]
Komponenta:
FZaposlenik

Commit:
e51cebc

Opis problema:
U SRS-u je navedeno sljedece: http://pokit.org/get/img/14f6c72379ca9bc2aa2feaf6dd3ad329.jpg
dok u vasoj aplikaciji otpad moze biti preko 20%

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Logovati se kao Zaposlenik
3. Kliknuti na tab Sastavnice
4. Povecati otpad na 21%

Dobijeni rezultat:
Otpad veci od 20% kako je receno u SRSu

Ocekivani rezultat:
Ogranicenost otpada na 20%

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: e88096ac249d32506b010da1f6e3a62de5f4147e
