### ISSUE TITLE
Brisanje sastavnice, plan za proizvodnju SRS

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#82]
Komponenta:
FMenadzer

Commit:
e51cebc

Opis problema:
U SRS-u je navedeno sljedece: http://pokit.org/get/img/a42b7c6c980d3fa5b88c75d3916ef01d.jpg
ne vidim nacina kako da se provjeri da li je proizvod u proizvodnji/planu za proizvodnju?

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Logovati se kao Menadzer
3. Kliknuti na tab Sastavnice

Dobijeni rezultat:
Ne pise nigdje podatak o proizvodnji

Ocekivani rezultat:
Sastavnica nije u proizvodnji / je u proizvodnji / je u planu za proizvodnju

**Comment by zlatancilic** [comment]
Ne mogu da razumijem o čemu se radi ovdje ni šta se pokušava uraditi. Sa slike ne vidim koja je akcija u pitanju, a ni koraci ne govore šta se pokušava uraditi?

**Comment by zloco** [comment]
pa to upravo zelim da mi ti kazes, gdje mogu vidjeti da li je proizvod u proizvodnji, odnosno smije li se obrisati ili ne smije?? na osnovu cega znas da je u proizvodnji?

**Comment by zlatancilic** [comment]
Pokusaj brisanja ne uspijeva ukoliko je proizvod u proizvodnji.
