### ISSUE TITLE
Pretraga po ID-u, SRS

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#83]
Komponenta:
FMenadzer

Commit:
e51cebc

Opis problema:
U SRS-u je navedeno sljedece: http://pokit.org/get/img/46056d295a66fc5807f82705b5c96c43.jpg
dok kod vas nudi pretrazivanje po nazivu i cijeni

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Logovati se kao Menadzer
3. Kliknuti na tab Sastavnice

Dobijeni rezultat:
Nema nacina da se sortira po ID-u

Ocekivani rezultat:
Sortiraj po: ID-u
Pretrazi po: ID-u

**Comment by benjaminBeganovic** [comment]
Ispravljeno u komitu: 267e2da3a4802376a2ebc2b2b6448c14b18c7e84
