### ISSUE TITLE
Kreiranje narudzbenice bez materijala

### ISSUE THREAD

**Issue by zloco** [SoftverInzenjeringETFSA/SI2014Tim1#84]
Komponenta:
FMenadzer

Commit:
e51cebc

Opis problema:
Pri kreiranju nove narudzbenice i doda se proizvod, pojavi se messagebox koji kaze da nije prethodno izabran materijal, zatim se ekran zamrzne i ne moze se izaci iz aplikacije ili bilo sta drugo uraditi u aplikaciji, nego se mora preko task managera ugasiti.

Korak za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "BOM"
2. Logovati se kao Menadzer
3. Kliknuti na tab Narudzbenice
4. Kliknuti na dugme Kreiraj
5. Unijeti serijski broj proizvoda
6. Kliknuti na dugme Dodaj proizvod
7. Kliknuti na dugme Kreiraj

Dobijeni rezultat:
Pada aplikacija i zamrzne se ekran

Ocekivani rezultat:
Samo messagebox o neuspjesnom dodavanju proizvoda bez materijala, ili skroz onemoguciti da se moze kliknuti dugme Kreiraj narudzbenicu bez materijala

**Comment by ArnelaBesic** [comment]
Ispravljeno kroz zabranu kreiranje narudžbenice bez materijala te popravku poziva prethodnog jframe-a
Commit: 0f2a3ab16baf8c6cb67f4404ed81f6844ba466e1
