### ISSUE TITLE
Dodavanje korisnika, pogresan upis u bazu

### ISSUE THREAD

**Issue by farisodobasic** [SoftverInzenjeringETFSA/SI2014Tim1#86]
Komponenta :
Forma "Korisnici" i "Kreiraj korisnika"

Commit : 
 e51cebcc647070bd7daad204320a711af9a1c63d
Opis problema : 
Nakon kreiranja korisnika na formi "Korisnici" u tabeli "Pregled/odabir korisnika" u koloni email ispisuje jmbg tog novog dodanog korisnik. 

Koraci za reproduciranje problema :
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara menadzeru (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.U gornjem desnom uglu pritisnuti dugme "Korisnici"
3.Odabrati dugme "Kreiraj" koje je unutra groupboxa "Novi korisnik"
4.Unijeti validne podatke u formu
5.Odabrati dugme "Kreiraj"

Dobijeni rezultat : 
U navedenoj tabeli se prikazuje jmbg umjesto emaila
![10](https://cloud.githubusercontent.com/assets/11445946/7896765/4455509a-06c5-11e5-98ff-29cf646470c4.png)

Očekivani rezultat : 
Očekuje se da se prikaže email korisnika, koji bi izgleda trebao da se automatski generiše obzirom da se nigdje ne unosi email novog korisnika

**Comment by nerminaagovic** [comment]
Popravljeno, commit: f655a24bf32ef65297e2bc7f26beb67688515240.

**Comment by CSharpQueen** [comment]
Popravljeno, dodano polje email na formu, commit: f655a24.
