### ISSUE TITLE
Nedovoljno informativna poruka na errorprovideru (dodavanje korisnika)

### ISSUE THREAD

**Issue by farisodobasic** [SoftverInzenjeringETFSA/SI2014Tim1#87]
Komponenta : 
FKorisnikDMP.java (Kreiranje korisnika)

Commit : 
 e51cebcc647070bd7daad204320a711af9a1c63d

Opis problema : 
Tokom kreiranja novog korisnika u nekim slučajevima pri unosu korisničkog imena se pojavi errorProvider sa porukom "Molimo uneste ispravno korisničko ime". Problem je nedovoljno informativna poruka. Da li treba određena dužina korisnčkog imena, da li treba da sadrži broj, samo slova itd.

Koraci za reproduciranje problema  :
Koraci za reproduciranje problema :
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara menadzeru (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.U gornjem desnom uglu pritisnuti dugme "Korisnici"
3.Odabrati dugme "Kreiraj" koje je unutra groupboxa "Novi korisnik"
4.Unijeti validne podatke u formu do korisničkog imena
5.Unijeti kao korisničko ime npr "kor"
6:Odabrati dugme "Kreiraj"

Dobijena rezultat :
Error provider sa neinformativnom porukom 
![9](https://cloud.githubusercontent.com/assets/11445946/7896846/19f6cb92-06c7-11e5-8935-5f7ae0168ead.png)

Očekivani rezultat : 
ErrorProvider sa porukom koja objašnjava u čemu je problem

**Comment by CSharpQueen** [comment]
Popravljeno, izmijenjene poruke o greskama za unos korisnickog imena i sifre, commit: f655a24bf32ef65297e2bc7f26beb67688515240.
