### ISSUE TITLE
Kreiranje korisnika bez šifre

### ISSUE THREAD

**Issue by farisodobasic** [SoftverInzenjeringETFSA/SI2014Tim1#88]
Komponenta :
FKorisnikDMP.java (Kreiranje korisnika)

Commit :
e51cebc

Opis problema : 
Moguće je kreirati korisnika bez da se unese polje šifra, pa takav korisnik se može prijaviti na sistem, što može da predstavlja sigurnosni propust. Dovoljno je da se pri prijavi unese njegovo korisničko ime, pa takav korisnik može da ima pristup svim podacima.

Koraci za reproduciranje problema :
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara menadzeru (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.U gornjem desnom uglu pritisnuti dugme "Korisnici"
3.Odabrati dugme "Kreiraj" koje je unutra groupboxa "Novi korisnik"
4.Unijeti validne podatke u formu do šifre
5.Polje šifra ostaviti prazno
6.Odabrati dugme "Kreiranj"
7.Odjaviti se
8.Prijaviti se sa korisničkim imenom korisnika kojeg smo prethodno dodali
9.Bez unošenja šifre prijaviti se

Dobijeni rezultat : 
Korisnik koje se bez šifre može prijaviti na sistem

Očekivani rezultat :
Upozorenje da nije unešena šifra pri kreiranju korisnika, i da takav ne može biti dodan.

**Comment by CSharpQueen** [comment]
Popravljeno, dodana validacija na polje za unos sifre, commit: f655a24bf32ef65297e2bc7f26beb67688515240.
