### ISSUE TITLE
Pregled postojećih korisnika 

### ISSUE THREAD

**Issue by farisodobasic** [SoftverInzenjeringETFSA/SI2014Tim1#89]
Komponenta : 
FKorisnikDMP - pregled korisnika

Commit : 
e51cebc

Koraci za reproduciranje problema : 
Koraci za reproduciranje problema :
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara menadzeru (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.U gornjem desnom uglu pritisnuti dugme "Korisnici"
3.Odabrati jednog korisnika iz tabele za kojeg u koloni "Pozicija " piše da je zaposlenik
4.Odabrati dugme "Pregledaj"

Opis problema : 
Nakon selektovanja jednog od korisnika iz tabele "Pregle/odabir korisnika" za kojeg pise da je zaposlenik (kolona "pozicija") i odabira dugmeta "Pregledaj" otvara se forma sa podacima odabranog korisnika. U comoboboxu "Pozicija" stoji da je menadzer iako je u tabeli zaposlenk (i u bazi je unesen kao zaposlenik). Također u polju šifra se ispisuje email odabranog korisnika.

Dobijeni rezultat : 
Pogrešan podatak u comoboboxu "Pozicija " : 
![11](https://cloud.githubusercontent.com/assets/11445946/7897026/31f6c5b6-06cd-11e5-909e-dfd7fbd73b32.png)

Očekivani rezultat : 
Da se podaci iz tabele i na ovoj formi podudaraju.

**Comment by CSharpQueen** [comment]
Korigovano, commit: f655a24bf32ef65297e2bc7f26beb67688515240.
