### ISSUE TITLE
Modifikovanje postojećeg korisnika (pozicija korisnika)

### ISSUE THREAD

**Issue by farisodobasic** [SoftverInzenjeringETFSA/SI2014Tim1#90]
Komponenta :
FKorisnikDMP - pregled korisnika

Commit :
e51cebc

Opis problema :
Pri modifikaciji postojećeg korisnika moguće je odabrati poziciju korisnika. Kada se odabere combobox "Pozcija" ponuđeni su menadzer i 2 zaposlenika. Da li se radi o 2 tipa zaposlenika?

Koraci za reproduciranje problema : 
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara menadzeru (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.U gornjem desnom uglu pritisnuti dugme "Korisnici"
3.Odabrati jednog korisnika iz tabele korisnika
4.Odabrati dugme "Modifikuj"
5.Odabrati combobox "Pozicija"

Dobijeni rezultat  :
Menadzer i 2 zaposlenika : 
![12](https://cloud.githubusercontent.com/assets/11445946/7897053/f0ca8dec-06cd-11e5-81d6-0f9b58b88ae9.png)

Očekivani rezultat : 
Ako se radi o jednom tipu zaposlenika, onda se očekuje da se izlista menadzer i zaposlenik. Ukoliko se radi o više tipova zaposlenika onda se očekuje da se navede koji su to tipovi.

**Comment by CSharpQueen** [comment]
Popravljeno, commit: f655a24bf32ef65297e2bc7f26beb67688515240.
