### ISSUE TITLE
Dodaju se dva korisinika, pod istim korisnickim imenom

### ISSUE THREAD

**Issue by akadrispahic** [SoftverInzenjeringETFSA/SI2014Tim1#91]
Komponenta: Kreiranje korisnika
Commit :
e51cebc
Opis problema:
Prilikom kreiranja uspješno je dodatikorisnik, koji ima isto korisničko ime, kao već jedan koji je unese u bazi. Sistem nije izbacio grešku, da ima već jedan unesen korisnik, sa istim korisničkim imenom.

Koraci za reprodukciju:
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara menadzeru (npr Korisničko ime : prvimenadzer; šifra : prvimenadzer)
2.U gornjem desnom uglu pritisnuti dugme "Korisnici"
3.Odabere se dugme Klijenti
4.Odabere se dugme Kreiraj
5.Zatim se ispuni forma Kreiranje Korisnika

Dobijeni rezultati:

![pokit_4588e674d3f0faf985047d4c3f13ed0d](https://cloud.githubusercontent.com/assets/11389876/7898305/43b89c78-06fc-11e5-9bad-38b1ebef78fa.jpg)

Očekivani rezultati:
Izbaciti ErrorProvider sa porukom koja objašnjava u čemu je problem

**Comment by CSharpQueen** [comment]
Ispravljeno, korisnicko ime je jedinstveno za svakog korisnika. 
Commiti: f655a24bf32ef65297e2bc7f26beb67688515240
425e10758536415ca8e9db226ddbf14fb69e3204.
