### ISSUE TITLE
Kreiranje narudžbenice, ažuriran samo zadnje unesen serijski broj 

### ISSUE THREAD

**Issue by AhmAli** [SoftverInzenjeringETFSA/SI2014Tim1#93]
Komponenta:
FNarudzbenicaP.java

commit ID:
a2c8de1

Opis problema:
Kreiranje narudžbenice, pri unosu različitih serijskih brojeva ažuriran ostaje samo zadnje uneseni serijski broj. Svi prethodno uneseni serijski brojevi su prebrisani.

image
![image](https://cloud.githubusercontent.com/assets/6852893/7898466/5327feba-0701-11e5-8f46-2f98b2bc7c00.png)

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju 
2. Ulogovati se kao manedzer
3. Odabrati Narudžbenice tab.
4. Odabrati opciju Kreiraj 
5. Unijeti serijski broj 
6. Dodati proizvod
7. Unijeti novi serijski broj
8. Unijeti proizvod

Dobijeni rezultat:
Kreirana Narudžbenica sa serijskim brojem jednakom zadnje unesenom serijskom broju.

Očekivani rezultat:
Kreiranje narudžbenice sa svim unesenim serijskim brojevima respektivno proizvodima.

**Comment by ArnelaBesic** [comment]
Ovaj slijed koraka daje ispravan rezultat jer nakon koraka 6 nije odabrana opcija Kreiraj. Ako se nakon koraka 6  klikne Kreiraj, u slučaju uspješnog kreiranja, forma će se zatvoriti i za kreiranje sljedeće narudžbenice se mora ponovo pozvati taj frame.
