### ISSUE TITLE
Narudžbenice, pregled nove unesene narudžbenice ne prikazuje rezultate

### ISSUE THREAD

**Issue by AhmAli** [SoftverInzenjeringETFSA/SI2014Tim1#94]
Komponenta:
FNarudzbenicaP.java

commit ID:
a2c8de1

Opis problema:
Nakon kreiranja nove narudžbenice nije dostupan sam Pregled navedene narudžbenice.

![image](https://cloud.githubusercontent.com/assets/6852893/7898480/d7086d6e-0701-11e5-8022-2abe86b24b1a.png)

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju 
2. Ulogovati se kao manedzer
3. Odabrati Narudžbenice tab.
4. Odabrati opciju Kreiraj 
5. Unijeti serijski broj 
6. Dodati proizvod
7. Unijeti novi serijski broj
8. Unijeti proizvod
9. Odabrati opciju Kreiraj
10. Sa liste odabrati novu dodanu narudžbenicu
11. Odabrati opciju Pregledaj za odabranu narudžbenicu.

Dobijeni rezultat:
Nije dostupan prikaz narudžbenice.

Očekivani rezultat:
Prikaz narudžbenice.

**Comment by ArnelaBesic** [comment]
Dodana veza između stavkeNarudžbenice i Narudžbenice pozivom metode setNarudžbenicu kod stavke.
Commit :01f09b91a6a938fda026bac399bcb9c8e2c8bb9f
