### ISSUE TITLE
Kreiranje narudžbenice, isti serijski broj za različite proizvode

### ISSUE THREAD

**Issue by AhmAli** [SoftverInzenjeringETFSA/SI2014Tim1#95]
Komponenta:
FNarudzbenicaP.java

commit ID:
a2c8de1

Opis problema:
Kreiranje narudžbenice, mogućnost dodavanja više različitih proizvoda pod istim serijskim brojem.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju 
2. Ulogovati se kao manadzer
3. Odabrati Narudžbenice tab.
4. Odabrati opciju Kreiraj 
5. Unijeti serijski broj 
6. Dodati proizvod
7. Kliknuti nekoliko puta na Dodaj proizvod
8. Promjeniti opciju "proizvod" 
9. Dodati proizvod
10. Promjeniti opciju "klijent"
11. Dodati proizvod

Dobijeni rezultat:
Kreirana Narudžbenica sa jednim serijskim brojem za različite proizvode

Očekivani rezultat:
Neuspješno kreiranje

**Comment by ArnelaBesic** [comment]
Po ovom slijedu koraka, dobijen je rezultat koji je očekivan. Opcija Dodaj proizvod nema veze sa serijskim brojem Narudžbenice. Narudžbenica ima jedan serijski broj i više proizvoda. Ispravite slijed koraka jer ovako nije prijavljena nikakva greška.
