### ISSUE TITLE
Pretraga za sastavnice

### ISSUE THREAD

**Issue by akadrispahic** [SoftverInzenjeringETFSA/SI2014Tim1#96]
Komponenta:  Forma zaposlenika

Commit : 
e51cebc

Opis problema:
prilikom pretrage, ako se izabere sortiranje po nazivu, kao i pretraga po nazivu, ništa se ne desi.
Sistem ne vraća nikakvu poruku.

Koraci za reprodukciju:
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom za zaposlenika (npr Korisničko ime : prviradnik; šifra : prviradnik)
2.Odabrati Sastavnice
3. Odabrati na sortiraj po : nazivu
4.Odabrati na pretraži po : nazivu
5  Unijela tekst : PrvaSastavnica
6.Odabrati dugme  Prikaži Sve

Dobijeni rezultati:
![7](https://cloud.githubusercontent.com/assets/11389876/7898578/89ea5a30-0704-11e5-9a6c-8db8fe306fc8.jpg)

Očekivani rezultati:

Otvaranje neke druge forme na kojoj bi se prikazale sve sastavnice ili da u tabeli ispod budu prikazane one koje odgovaraju prema parametrima sortiranja i pretrage, ili Izbaciti ErrorProvider sa porukom koja objašnjava u čemu je problem

**Comment by CSharpQueen** [comment]
Isto kao #39
