### ISSUE TITLE
Pretraga za skladište

### ISSUE THREAD

**Issue by akadrispahic** [SoftverInzenjeringETFSA/SI2014Tim1#97]
Komponenta: Forma zaposlenika

Commit : 
e51cebc

Opis problema:
Prilikom pretrage za skladište, ako se izabere sortiranje po nazivu, kao i pretraga po nazivu, ništa se ne desi.
Sistem ne vraća nikakvu poruku.

Koraci za reprodukciju:
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom za zaposlenika (npr Korisničko ime : prviradnik; šifra : prviradnik)
2.Odabrati Skladište
3. Odabrati na sortiraj po : nazivu
4.Odabrati na pretraži po : nazivu
5 Unijela tekst : DrugaSastavnica
6.Odabrati dugme Prikaži Sve

Dobijeni rezultati:
![5](https://cloud.githubusercontent.com/assets/11389876/7898608/472e4430-0705-11e5-93df-5524af0b495e.jpg)

Očekivani rezultati:

Otvaranje neke druge forme na kojoj bi se rezulati pretrage ili da u tabeli ispod budu prikazane one koje odgovaraju prema parametrima sortiranja i pretrage, ili Izbaciti ErrorProvider sa porukom koja objašnjava u čemu je problem

**Comment by CSharpQueen** [comment]
Isto kao #40, ista forma.
