### ISSUE TITLE
Nemogućnost brisanja korisnika

### ISSUE THREAD

**Issue by AhmAli** [SoftverInzenjeringETFSA/SI2014Tim1#98]
Komponenta:
FKorisnikDMPB.java

commit ID:
e51cebcc647070bd7daad204320a711af9a1c63d

Opis problema:
Nije moguće obrisati korisnike.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju 
2. Ulogovati se kao manadzer
3. Odabrati button Korisnici
4. Odabrati korisnika
5. Izbrisati korisnika

![image](https://cloud.githubusercontent.com/assets/6852893/7898594/0084b230-0705-11e5-9ea0-75dabf438116.png)

Dobijeni rezultat:
PopUp window sa ispisom upozorenja "Ovog korisnika nije moguće izbrisati".

Očekivani rezultat:
Korisnik izbrisan

**Comment by CSharpQueen** [comment]
Korigovano, izmjenjena poruka o gresci pri brisanju, commit: df86933adb57b107a79d872fe05e6614119f1a1f.
