### ISSUE TITLE
Unos materijala/poluproizvoda

### ISSUE THREAD

**Issue by akadrispahic** [SoftverInzenjeringETFSA/SI2014Tim1#99]
Komponenta: FZaposlenik
Commit :
e51cebc

Opis problema:
Unesn materijal, medjutim ni jedno polje nije ispunjeno

Koraci za reprodukciju:
1.Pokrenuti desktop aplikaciju "BOM" kroz login formu (login.java) i prijaviti se sa korisnickim imenom koji odgovara zaposleniku (npr Korisničko ime : prviradnik; šifra : prviradnik)
2.Otvoriti polje skladište
3.Odabrati dugme Kreiraj
4. Odabrati dugme Unesi

Dobijeni rezultati:
![55](https://cloud.githubusercontent.com/assets/11389876/7898659/172ff09c-0707-11e5-913d-ee7432f34a8d.jpg)

Očekivani rezultati:
Izbaciti ErrorProvider sa porukom koja govori, da se ne može unijeti materijal a da polja nisu ispunjena.

**Comment by CSharpQueen** [comment]
Isto kao #64
